export const GET_RESTAURANTS_SUCCESS = 'GET_RESTAURANTS_SUCCESS';
export const GET_RESTAURANT_SUCCESS = 'GET_RESTAURANT_SUCCESS'

export const GET_RESTAURANT_PLACES_SUCCESS = 'GET_RESTAURANT_PLACES_SUCCESS'